apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT_NAME
  namespace: NAMESPACE
  labels:
    app: PROJECT
spec:
  selector:
    matchLabels:
      project: PROJECT
  template:
    metadata:
      namespace: NAMESPACE
      labels:
        project: PROJECT
    spec:
      containers:
         - name: PROJECT
           image: REGISTRY_HOSTNAME/PROJECT:TAG_VERSION
           ports:
             - containerPort: PORT_CONTAINER

           env:
             - name: FILES_SERVICE_HOST
               valueFrom:
                 secretKeyRef:
                   name: files-service-production-config-secret
                   key: FILES_SERVICE_HOST
             - name: MONGO_URL
               valueFrom:
                 secretKeyRef:
                   name: files-service-production-config-secret
                   key: MONGO_URL
             - name: FILES_SERVICE_PORT
               valueFrom:
                 secretKeyRef:
                   name: files-service-production-config-secret
                   key: FILES_SERVICE_PORT
