apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT_NAME
  namespace: NAMESPACE
  labels:
    app: PROJECT
spec:
  selector:
    matchLabels:
      project: PROJECT
  template:
    metadata:
      namespace: NAMESPACE
      labels:
        project: PROJECT
    spec:
      containers:
         - name: PROJECT
           image: REGISTRY_HOSTNAME/PROJECT:TAG_VERSION
           ports:
             - containerPort: PORT_CONTAINER

           env:
             - name: DIRECT_URL
               valueFrom:
                 secretKeyRef:
                   name: main-service-production-config-secret
                   key: DIRECT_URL
             - name: PROD_URL
               valueFrom:
                 secretKeyRef:
                   name: main-service-production-config-secret
                   key: PROD_URL
             - name: GOOGLE_PASSWORD
               valueFrom:
                 secretKeyRef:
                   name: main-service-production-config-secret
                   key: GOOGLE_PASSWORD
             - name: JWT_SECRET_KEY
               valueFrom:
                 secretKeyRef:
                   name: main-service-production-config-secret
                   key: JWT_SECRET_KEY
             - name: JWT_REFRESH_KEY
               valueFrom:
                 secretKeyRef:
                   name: main-service-production-config-secret
                   key: JWT_REFRESH_KEY
             - name: JWT_EXPIRATION_TIME
               valueFrom:
                 secretKeyRef:
                   name: main-service-production-config-secret
                   key: JWT_EXPIRATION_TIME
             - name: JWT_REFRESH_EXPIRATION_TIME
               valueFrom:
                 secretKeyRef:
                   name: main-service-production-config-secret
                   key: JWT_REFRESH_EXPIRATION_TIME
             - name: NODE_ENV
               valueFrom:
                 secretKeyRef:
                   name: main-service-production-config-secret
                   key: NODE_ENV
             - name: RECAPTCHA_SECRET
               valueFrom:
                 secretKeyRef:
                   name: main-service-production-config-secret
                   key: RECAPTCHA_SECRET
             - name: GOOGLE_CLIENT_ID
               valueFrom:
                 secretKeyRef:
                   name: main-service-production-config-secret
                   key: GOOGLE_CLIENT_ID
             - name: GOOGLE_CLIENT_SECRET
               valueFrom:
                 secretKeyRef:
                   name: main-service-production-config-secret
                   key: GOOGLE_CLIENT_SECRET
             - name: GITHUB_CLIENT_ID
               valueFrom:
                 secretKeyRef:
                   name: main-service-production-config-secret
                   key: GITHUB_CLIENT_ID
             - name: GITHUB_CLIENT_SECRET
               valueFrom:
                 secretKeyRef:
                   name: main-service-production-config-secret
                   key: GITHUB_CLIENT_SECRET
             - name: DATABASE_URL
               valueFrom:
                 secretKeyRef:
                   name: main-service-production-config-secret
                   key: DATABASE_URL
